/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Watcom C++
*/

#include <defs.h>



//----- (00010008) --------------------------------------------------------
#error "10008: only 32bit functions can be decompiled (funcsize=0)"

//----- (00010057) --------------------------------------------------------
#error "10057: only 32bit functions can be decompiled (funcsize=0)"

//----- (000101BA) --------------------------------------------------------
#error "101BA: only 32bit functions can be decompiled (funcsize=0)"

//----- (000101D8) --------------------------------------------------------
#error "101D8: only 32bit functions can be decompiled (funcsize=0)"

//----- (000101DC) --------------------------------------------------------
#error "101DC: only 32bit functions can be decompiled (funcsize=0)"

//----- (000104B1) --------------------------------------------------------
#error "104B1: only 32bit functions can be decompiled (funcsize=0)"

//----- (000112C9) --------------------------------------------------------
#error "112C9: only 32bit functions can be decompiled (funcsize=0)"

//----- (00011335) --------------------------------------------------------
#error "11335: only 32bit functions can be decompiled (funcsize=0)"

//----- (00011356) --------------------------------------------------------
#error "11356: only 32bit functions can be decompiled (funcsize=0)"

//----- (0001142A) --------------------------------------------------------
#error "1142A: only 32bit functions can be decompiled (funcsize=0)"

//----- (00011696) --------------------------------------------------------
#error "11696: only 32bit functions can be decompiled (funcsize=0)"

//----- (000117A4) --------------------------------------------------------
#error "117A4: only 32bit functions can be decompiled (funcsize=0)"

//----- (00011DA2) --------------------------------------------------------
#error "11DA2: only 32bit functions can be decompiled (funcsize=0)"

//----- (00011FF3) --------------------------------------------------------
#error "11FF3: only 32bit functions can be decompiled (funcsize=0)"

//----- (000124E1) --------------------------------------------------------
#error "124E1: only 32bit functions can be decompiled (funcsize=0)"

#error "There were 15 decompilation failure(s) on 15 function(s)"
